### ISSUE TITLE
[BUG]重新安装1.8.5版本服务无法启动,goroutine 提示异常

### ISSUE THREAD

**Issue by lynn5713** [morytyann/OpenWrt-mihomo#226]
### 自查

- [X] OpenWrt 22.03 及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经安装了 procd-ujail 依赖
- [X] 针对ImmortalWrt，已经关闭了DNSMASQ的`DNS 重定向`选项
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建的插件，而不是其他Fork
- [X] 我使用的是最新版的插件
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题
- [X] 我提供了正确的、有效的、可以帮助DEBUG的信息，而不是随意填写
- [X] 我提供的信息里不包含公网IP、MAC、代理节点等敏感信息

### 系统

OpenWrt

### 系统版本

23.05

### 插件版本

1.8.5-1

### 硬件架构

mipsel_24kc

### BUG 描述

time="2024-10-09T09:55:31.228431339+08:00" level=info msg="Start initial configuration in progress"
time="2024-10-09T09:55:31.27538941+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-10-09T09:55:31.27590394+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-10-09T09:55:31.30253985+08:00" level=info msg="Can't find GeoIP.dat, start download"
panic: should never be called

goroutine 53 [running]:
main.main.func1({0x1853e70, 0x30c59a0}, {0x1656489, 0x3}, {0x33a0240, 0xc})
	github.com/metacubex/mihomo/main.go:63 +0x50
net.(*Resolver).dial(0x2145e60, {0x1853e70, 0x30c59a0}, {0x1656489, 0x3}, {0x33a0240, 0xc})
	net/lookup.go:684 +0x88
net.(*Resolver).exchange(0x2145e60, {0x1853e38, 0x32b9230}, {0x33a0240, 0xc}, {{{0x6d, 0x69, 0x72, 0x72, 0x6f, ...}, ...}, ...}, ...)
	net/dnsclient_unix.go:184 +0x390
net.(*Resolver).tryOneName(0x2145e60, {0x1853e38, 0x32b9230}, 0x30b1b00, {0x32dcfd8, 0x13}, 0x1c)
	net/dnsclient_unix.go:315 +0x4a0
net.(*Resolver).goLookupIPCNAMEOrder.func3.1(0x1c)
	net/dnsclient_unix.go:668 +0x98
created by net.(*Resolver).goLookupIPCNAMEOrder.func3 in goroutine 51
	net/dnsclient_unix.go:667 +0x184

### 预期行为

正常启动核心

### 复现步骤

重新安装，常见现象

### 插件配置

root@ImmortalWrt:~# uci show mihomo
mihomo.status=status
mihomo.config=config
mihomo.config.enabled='1'
mihomo.config.scheduled_restart='0'
mihomo.config.cron_expression='0 3 * * *'
mihomo.config.profile='file:mihomo.yaml'
mihomo.config.mixin='1'
mihomo.config.test_profile='1'
mihomo.config.fast_reload='0'
mihomo.config.upload_profile='/etc/mihomo/profiles/mihomo.yaml'
mihomo.proxy=proxy
mihomo.proxy.transparent_proxy='1'
mihomo.proxy.tcp_transparent_proxy_mode='tproxy'
mihomo.proxy.udp_transparent_proxy_mode='tproxy'
mihomo.proxy.ipv4_dns_hijack='1'
mihomo.proxy.ipv6_dns_hijack='1'
mihomo.proxy.ipv4_proxy='1'
mihomo.proxy.ipv6_proxy='0'
mihomo.proxy.router_proxy='1'
mihomo.proxy.lan_proxy='1'
mihomo.proxy.access_control_mode='all'
mihomo.proxy.bypass_china_mainland_ip='0'
mihomo.proxy.acl_tcp_dport='0-65535'
mihomo.proxy.acl_udp_dport='0-65535'
mihomo.subscription=subscription
mihomo.subscription.name='default'
mihomo.subscription.url='https://abc.com'
mihomo.subscription.user_agent='clash'
mihomo.mixin=mixin
mihomo.mixin.log_level='info'
mihomo.mixin.mode='rule'
mihomo.mixin.match_process='off'
mihomo.mixin.ipv6='0'
mihomo.mixin.tcp_keep_alive_idle='600'
mihomo.mixin.tcp_keep_alive_interval='15'
mihomo.mixin.ui_name='metacubexd'
mihomo.mixin.ui_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip'
mihomo.mixin.api_port='9090'
mihomo.mixin.selection_cache='1'
mihomo.mixin.allow_lan='1'
mihomo.mixin.http_port='8080'
mihomo.mixin.socks_port='1080'
mihomo.mixin.mixed_port='7890'
mihomo.mixin.redir_port='7891'
mihomo.mixin.tproxy_port='7892'
mihomo.mixin.authentication='1'
mihomo.mixin.tun_stack='system'
mihomo.mixin.tun_mtu='9000'
mihomo.mixin.tun_gso='1'
mihomo.mixin.tun_gso_max_size='65536'
mihomo.mixin.tun_endpoint_independent_nat='0'
mihomo.mixin.dns_port='1053'
mihomo.mixin.dns_mode='fake-ip'
mihomo.mixin.fake_ip_range='198.18.0.1/16'
mihomo.mixin.fake_ip_filter='0'
mihomo.mixin.fake_ip_filters='+.lan' '+.local'
mihomo.mixin.fake_ip_cache='1'
mihomo.mixin.dns_respect_rules='0'
mihomo.mixin.dns_doh_prefer_http3='0'
mihomo.mixin.dns_ipv6='0'
mihomo.mixin.dns_system_hosts='0'
mihomo.mixin.dns_hosts='0'
mihomo.mixin.hosts='0'
mihomo.mixin.dns_nameserver='0'
mihomo.mixin.dns_nameserver_policy='0'
mihomo.mixin.geoip_format='dat'
mihomo.mixin.geodata_loader='memconservative'
mihomo.mixin.geosite_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat'
mihomo.mixin.geoip_mmdb_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb'
mihomo.mixin.geoip_dat_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat'
mihomo.mixin.geoip_asn_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb'
mihomo.mixin.geox_auto_update='0'
mihomo.mixin.geox_update_interval='24'
mihomo.mixin.api_secret='588714'
mihomo.@authentication[0]=authentication
mihomo.@authentication[0].enabled='1'
mihomo.@authentication[0].username='mihomo'
mihomo.@authentication[0].password='588714'
mihomo.@host[0]=host
mihomo.@host[0].enabled='0'
mihomo.@host[0].domain_name='localhost'
mihomo.@host[0].ip='127.0.0.1' '::1'
mihomo.@nameserver[0]=nameserver
mihomo.@nameserver[0].enabled='1'
mihomo.@nameserver[0].type='default-nameserver'
mihomo.@nameserver[0].nameserver='223.5.5.5' '119.29.29.29'
mihomo.@nameserver[1]=nameserver
mihomo.@nameserver[1].enabled='1'
mihomo.@nameserver[1].type='proxy-server-nameserver'
mihomo.@nameserver[1].nameserver='https://dns.alidns.com/dns-query' 'https://doh.pub/dns-query'
mihomo.@nameserver[2]=nameserver
mihomo.@nameserver[2].enabled='1'
mihomo.@nameserver[2].type='nameserver'
mihomo.@nameserver[2].nameserver='https://dns.alidns.com/dns-query' 'https://doh.pub/dns-query'
mihomo.@nameserver[3]=nameserver
mihomo.@nameserver[3].enabled='0'
mihomo.@nameserver[3].type='fallback'
mihomo.@nameserver[3].nameserver='https://dns.cloudflare.com/dns-query' 'https://dns.google/dns-query'
mihomo.@nameserver_policy[0]=nameserver_policy
mihomo.@nameserver_policy[0].enabled='1'
mihomo.@nameserver_policy[0].matcher='geosite:cn,private'
mihomo.@nameserver_policy[0].nameserver='https://dns.alidns.com/dns-query' 'https://doh.pub/dns-query'
mihomo.@nameserver_policy[1]=nameserver_policy
mihomo.@nameserver_policy[1].enabled='1'
mihomo.@nameserver_policy[1].matcher='geosite:geolocation-!cn'
mihomo.@nameserver_policy[1].nameserver='https://dns.cloudflare.com/dns-query' 'https://dns.google/dns-query'
mihomo.editor=editor
mihomo.log=log

### 配置文件

proxy-providers:
  paofu:
    type: http
    interval: 1800
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
    proxy: 🟢 直连
    url: "abc.com"
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.push.apple.com"
    - "+.apple.com"
proxies:
- name: "🟢 直连"
  type: direct
  udp: true

proxy-groups:
  - {name: 🤖 copilot, type: url-test, include-all: true, filter: "(?i)台湾|新加坡|日本|美国"}
  - {name: 🚀 节点选择, type: select, proxies: [🇭🇰 香港节点, 🇯🇵 日本节点, 🇺🇲 美国节点, 🇹🇼 台湾节点, 🇸🇬 新加坡, 🟢 直连]}
  - {name: ♻️ Auto, type: url-test, proxies: [🌐 全部节点]}
  - {name: 🕘 Speedtest, type: select, proxies: [🟢 直连, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇺🇲 美国节点, 🇹🇼 台湾节点, 🇸🇬 新加坡]}
  - {name: 🎯 全球直连, type: select, proxies: [🟢 直连, 🚀 节点选择]}
  - {name: 🪟 Microsoft, type: select, proxies: [🟢 直连, 🤖 copilot]}
  - {name: ⏮️ final, type: select, proxies: [♻️ Auto, 🟢 直连]}
  - {name: 🇭🇰 香港节点, type: url-test, include-all: true, filter: "(?i)港|hk|hongkong|hong kong"}
  - {name: 🇯🇵 日本节点, type: url-test, include-all: true, filter: "(?i)日|jp|japan"}
  - {name: 🇺🇲 美国节点, type: url-test, include-all: true, filter: "(?i)美|us|unitedstates|united states"}
  - {name: 🇹🇼 台湾节点, type: url-test, include-all: true, filter: "(?i)台湾|tw|TW"}
  - {name: 🇸🇬 新加坡, type: url-test, include-all: true, filter: "(?i)新加坡|sg|SG"}
  - {name: 🌐 全部节点, type: url-test, include-all: true}
rules:
  - GEOSITE,category-ads-all,REJECT
  - RULE-SET,copilot,🤖 copilot
  - GEOSITE,apple-cn,🎯 全球直连
  - GEOSITE,microsoft@cn,🎯 全球直连
  - GEOSITE,private,🎯 全球直连
  - GEOSITE,github,♻️ Auto
  - GEOSITE,youtube,♻️ Auto
  - GEOSITE,google,♻️ Auto
  - GEOSITE,onedrive,🎯 全球直连
  - GEOSITE,microsoft,🪟 Microsoft
  - GEOSITE,tiktok,🤖 copilot
  - GEOSITE,speedtest,🕘 Speedtest
  - GEOSITE,telegram,♻️ Auto
  - GEOSITE,netflix,♻️ Auto
  - GEOSITE,paypal,♻️ Auto
  - GEOSITE,geolocation-!cn,♻️ Auto
  - GEOSITE,cn,🎯 全球直连
  - GEOIP,google,♻️ Auto,no-resolve
  - GEOIP,netflix,♻️ Auto,no-resolve
  - GEOIP,telegram,♻️ Auto,no-resolve
  - GEOIP,cn,🎯 全球直连,no-resolve
  - MATCH,⏮️ final
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  qcy: &qcy {type: http, interval: 86400, behavior: domain, format: text}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  copilot: {   <<: *class, url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Copilot/Copilot.list" }

### 插件日志

[2024-10-09 10:17:41] App is enabled.
[2024-10-09 10:17:41] Starting...
[2024-10-09 10:17:41] Use Profile: mihomo.yaml
[2024-10-09 10:17:41] Mixin is enabled, mixin all config.
[2024-10-09 10:17:42] Profile testing...
[2024-10-09 10:17:42] Profile test failed!
[2024-10-09 10:17:42] Exiting...

### 核心日志

time="2024-10-09T10:11:18.947542746+08:00" level=info msg="Start initial configuration in progress"
time="2024-10-09T10:11:18.99488064+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-10-09T10:11:18.995228304+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-10-09T10:11:19.023999601+08:00" level=info msg="Can't find GeoIP.dat, start download"
panic: should never be called

goroutine 6 [running]:
main.main.func1({0x1853e70, 0x44a8cd0}, {0x1656489, 0x3}, {0x47ae9b0, 0xc})
	github.com/metacubex/mihomo/main.go:63 +0x50
net.(*Resolver).dial(0x2145e60, {0x1853e70, 0x44a8cd0}, {0x1656489, 0x3}, {0x47ae9b0, 0xc})
	net/lookup.go:684 +0x88
net.(*Resolver).exchange(0x2145e60, {0x1853e38, 0x4850330}, {0x47ae9b0, 0xc}, {{{0x6d, 0x69, 0x72, 0x72, 0x6f, ...}, ...}, ...}, ...)
	net/dnsclient_unix.go:184 +0x390
net.(*Resolver).tryOneName(0x2145e60, {0x1853e38, 0x4850330}, 0x47c9ce0, {0x4921a10, 0x13}, 0x1c)
	net/dnsclient_unix.go:315 +0x4a0
net.(*Resolver).goLookupIPCNAMEOrder.func3.1(0x1c)
	net/dnsclient_unix.go:668 +0x98
created by net.(*Resolver).goLookupIPCNAMEOrder.func3 in goroutine 4
	net/dnsclient_unix.go:667 +0x184

**Comment by lynn5713** [comment]
> [MetaCubeX/mihomo#1572](https://github.com/MetaCubeX/mihomo/issues/1572)

root@ImmortalWrt:/etc/mihomo/run# pwd
/etc/mihomo/run
 wget https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
wget  https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
